### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#27]
install It is already the newest version of the mono -complete .
http://prntscr.com/ah64an
http://prntscr.com/ah60pj

I put the mono version of the same 3.6

**Comment by emperorstarfinder** [comment]
Fixed. Thanks for the report

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
http://prntscr.com/ah9oj4 its norm?

**Comment by emperorstarfinder** [comment]
Those are fine.  They don't break the physics engines and are just warnings.  If all you get are warnings the build should be successful.  Also keep in mind our physics engine developer is still working on updates to the physics engines so some warnings maybe due to changes she is making.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
New error http://prntscr.com/ah9qvg

**Comment by emperorstarfinder** [comment]
According to that error you are using Mono 3.6.0 The latest version and the one we test against is Mono 4.2.3.4 which you need to install following the directions for Ubuntu here: 

Adding the repositories to your apt list:

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list

sudo apt-get update

Installing mono

Once we add the apt repositories as stated above we do the following:

Mono-Devel = sudo apt-get install mono-devel

Let it install and complete, then next

Mono-Complete = sudo apt-get install mono-complete

Let it install and complete, then next

Reference Assemblies

ReferenceAssemblies-PCL = sudo apt-get install referenceassemblies-pcl

Let it install and complete, then next

Mono certificates

CA-Certificates-Mono = sudo apt-get install ca-certificates-mono

Let it install and complete 

Once you installed mono do

sudo apt-get update && sudo apt-get upgrade

That command will update the apt list and will tell you if you need any upgrades.  If so type Y and hit enter and it will upgrade the necessary files.  Then reboot the server  This will give you the Ubuntu operating system fully updated and the current version of mono.  Then you shouldn't get that error.  

In any event that is not an error caused it appears by Virtual Universe its likely because of a missing file within mono itself.

It is very much possible this error is just an anomaly but you should keep mono at the latest version as that is what we test against.  

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
How to remove mono 3.6?(

**Comment by LifeGold** [comment]
Did all the instructions above and now writes but does not collect the server http://prntscr.com/ahbh34

**Comment by emperorstarfinder** [comment]
It sounds like you removed mono.  if you have followed the directions to
add the mono apt apt repository as I indicated just do the install steps I
provided in the order I provided.  That will install Mono 4.2.3.4

If needed with remote access I could go in and install mono for you but
you would need to set up the remote desktop stuff on ubuntu and provide a
username and password.

**Comment by LifeGold** [comment]
Work.

**Comment by emperorstarfinder** [comment]
So you got it working?

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
http://prntscr.com/ahejc0

**Comment by emperorstarfinder** [comment]
You should really try to just clone the repository using git or smartgit.  Sometimes github gets fussy and files that are actually there show up as missing.  So I would clone the repository.

**Comment by LifeGold** [comment]
No difference with how github writes the same thing.

**Comment by emperorstarfinder** [comment]
There will be a major commit pushed shortly that should fix alot of problems.  When I do a test build I will push a copy of the built bin to our project website

**Comment by LifeGold** [comment]
It's good but need to compile myself since a lot of the changes includes the WebUI

**Comment by emperorstarfinder** [comment]
Closing as this issue should now be moot with last nights commits
