### ISSUE TITLE
Web error

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#32]
The list of users in the network is visible only to administrators. With a regular account http://prntscr.com/ahdzpw With the administrator account http://prntscr.com/ahe05a

**Comment by emperorstarfinder** [comment]
The best thing to do here would be to have you send me a copy of your source code and your bin folder that you have built so I can look and see what is going on.  I am actually not sure why that would be occurring here.

**Comment by LifeGold** [comment]
Still need to break in layers and display information in the menu on levels.
Look on the server are moderators, give them full access this search.
I propose to make for example 100 the level of moderator in the site menu if the user of this level to leave only the page with the ban time.
For level 200 for example to leave all but the tab menu Manager
and level 250 to assign full rights to the website.

**Comment by emperorstarfinder** [comment]
The system already does that

God Levels are:

100 = Customer Service (This would be your normal administrative staff)
250 = Full Grid God ability (Grid developers)

These user levels allow users assigned to that level to see more then normal users with customer service level users seeing less then full grid god user level.

**Comment by LifeGold** [comment]
Checked, I have a website which is 100 to 250 which gives full access(

**Comment by emperorstarfinder** [comment]
We will be making some adjustments in upcoming versions to provide for more security and protection of staff accounts so the best thing would be to wait on messing with the user levels and just let the current settings we have for handling that remain in place the webui works with it at the present time but we are working on more pieces to this as we add the marketplace stuff in

**Comment by greythane** [comment]
This is a security measure to assist in the prevention of spamming etc.
Admins can search/see all users whilst logged in users can only search/see their friends.

Btw. I would be interested in these changes to the WebUi as discussed as this is on my list of "things to do"

**Comment by emperorstarfinder** [comment]
@greythane speaking of security measures one of our Core Developers here stumbled on a rather interesting security exploit in a file used to replace another file in viewers.  We might need to have a discussion at some point about how to check to be sure the viewers connecting to the architecture are legitimate and don't have hacked files being used that are harmful.

As far as the upcoming changes to the admin accounts

These changes we are working on are to allow easier handling while providing extra security and safeguards to prevent unnecessary use and unauthorized uses on the system.  As an example staff accounts without the necessary authorization levels wont be able to handle issues pertaining to currency related issues.  This is only just an example of course as some of these items are still being discussed internally.  

Some things that staff with UserLevel 100 can do similar things as staff with UserLevel 250, however the key LifeGold was proposing is parsing this and making sure each level has a set of distinct abilities.

Also he has made some interesting design changes to his builtin webui for Virtual Universe which Virtual Universe itself might adopt as soon as he passes us the files we need to see to make a decision regarding implementation.  You can see those styling changes at http://reallife3d.ru:8002

He does need to keep the translator buttons in place however because not everyone will speak the same language.

**Comment by emperorstarfinder** [comment]
Moving discussion of ideas for new features and enhancements to the webUI to Issue #33 so we wont be confused as this issue was opened based on a potential bug.  Thanks.

**Comment by emperorstarfinder** [comment]
For reference relating to LifeGold's question regarding userlevels These can be found in Universe/Framework/Utilities/Constants.cs

        // user levels
        public const int USER_DISABLED = -2;
        public const int USER_BANNED = -1;
        public const int USER_NORMAL = 0;
        public const int USER_GOD_LIKE = 1;                 
        public const int USER_GOD_CUSTOMER_SERVICE = 100;
        public const int USER_GOD_LIASON = 150;
        public const int USER_GOD_FULL = 200;
        public const int USER_GOD_MAINTENANCE = 250;

The WebUI will read these already from the database.

**Comment by emperorstarfinder** [comment]
Closing as this is not really an error.  Issue #33 is for discussion of new features to be implemented in both the builtin webUI and the standalone
