### ISSUE TITLE
Error thrown with user_currency table

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#46]
When you log on to the website on the page of the Transaction http://prntscr.com/azxu1w

**Comment by emperorstarfinder** [comment]
Yes this is a bug we are in the process of fixing as we speak :)

**Comment by LifeGold** [comment]
PAGE MANAGER Not working

**Comment by emperorstarfinder** [comment]
I just have a little more testing to do on this bug, however it appears the new tables were not loading correctly.  I have an upcoming commit that will clean up all the database tables anyway so that should fix this issue.

**Comment by emperorstarfinder** [comment]
I have fixed this bug in the system.  This bug is one that affects only current users in your database and not new users created after.  Essentially the rows aren't being changed in the data added for each user which is causing this.  The easiest fix would be to start your database from scratch and create a new account for the user.

**Comment by emperorstarfinder** [comment]
This has been resolved.  It is advised that users start with a fresh database to ensure all users who register on your grid get the updated currency tables.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
