### ISSUE TITLE
The new design of the web site

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#48]
Привет всем. Хочу представить первую версию изменённого веб сайта для серверa Virtual Universe. Полностью изменен дизайн сайта, переписан весь код на 
css, html, javascript. Так же внесены минимальные изменения в исходный код сайта на C#. 
Сайт полностью совместим с версией сервера 1.0.2 RC2. И работает без ошибок. С сайта полностью удалены страницы которые на данный момент
являются нерабочими. Список ниже.

1. История Транзакций.
2. Пользователи онлайн. Работает только если на аккаунте статус админа.
3. Временно отключен список локаций, будет доступен в следующей версии сайта. В связи с внесением изменений в исходный код.
4. Восстановление пароля. 
5. Поиск по пользователя.
* И другие страницы которые на данный момент не рабочие.

В админ панель изменения пока не вносились, они будут доступны на днях по ссылке ниже. Там также очень много нерабочего и лишнего.
Также постоянное обновление Русского языка в связи с добавление и изменением веб сайта.
В следующей версии сайта будет доступен Украинский язык.

https://github.com/ReaL-Life-3D/VU-Web-Site-Redesing

******************************************************************************************************************************* Translated with Google
*******************************************************************************************************************************

Hi all. I want to introduce the first version of the modified web site to the Virtual Universe server. A fully redesigned website, rewritten all of the code on 
css, html, javascript. Also made minimal changes to the source code of the website in C#. 
The site is fully compatible with the server version 1.0.2 RC2. And runs without errors. From the site permanently deleted page which at the moment
are non-working. The list below.

1. The Transaction History.
2. Users online. Only works if the account status is admin.
3. Temporarily disabled the list of locations will be available in the next version of the site. In connection with changes in the source code.
4. Password recovery. 
5. Search by user.
* And other pages which are currently not working.

In the admin panel changes have not yet been made, they will be available on the day from the link below. There are also very a lot of invalid and redundant.
Continuous updating of the Russian language in connection with the addition and change of the web site.
In the next version of the site will be available to the Ukrainian language.

https://github.com/ReaL-Life-3D/VU-Web-Site-Redesing

**Comment by emperorstarfinder** [comment]
You can always fork our repository locally and commit changes to your fork of the Virtual-Universe repository and then submit a pull request for our review and integration.  We do ask that you do commit changes to a branch on your fork of the Virtual-Universe repository on github and submit the pull request from that branch.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by IrishwolfStarfinder** [comment]
Website is looking good.  I will go through it as I am going to be
starting the overhaul this week.  It will appear in the Development
Repository: https://github.com/Virtual-Universe/Virtual-Dev  as it will
not be introduced until Version 1.0.3.

Also you reference whitecore-sim.org in slmapapi.js line number 748 you
reference as follows:

var copyright = new GCopyright(1, new GLatLngBounds(new GLatLng(0, 0), new
GLatLng(-90, 90)), 0, "(C) 2014 - " + (new Date).getFullYear() + "
WhiteCore-Sim.org");

That is incorrect referencing.  Virtual Universe is its own project and
architecture and is not part of WhiteCore-Sim.  The correct reference
should be:

var copyright = new GCopyright(1, new GLatLngBounds(new GLatLng(0, 0), new
GLatLng(-90, 90)), 0, "(C) 2015-2025 - " + (new Date).getFullYear() + "
virtual-planets.org");

While it is true that some of our base code came from the developers of
WhiteCore-Sim, Virtual Universe is its own architecture and is owned by
the Second Galaxy Development Team.  Our team leader represents our team
with WhiteCore-Sim and one of their developers is a collaborating partner
on the Virtual Universe team representing WhiteCore-Sim.

I should push the initial code implementing this stuff in the next day or
two.  Great work so far :)

Irishwolf Starfinder
Core Developer
Web and Network Design
Group Member
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
Didn't notice the link to WhiteCore-Sim.org will fix in the morning)

**Comment by greythane** [comment]
Please be careful about removing copyright notices relating to WhiteCore otherwise I might get very offended.... and it is part of the copyright agreement anyway.

**Comment by emperorstarfinder** [comment]
@LifeGold Not a problem.

@greythane Yes I do agree we should always be careful about the licensing piece.  The line of code I was pointing to appears to be what is being shown at the bottom of the page in the browser which should in theory say the copyright of the site URL.  I am aware that there is discussion going on between WhiteCore-Sim developers and our lead developer here relating to licensing.  One thing I might suggest to ensure we cover licensing until we have a clear path agreed on would be put the licensing even at the top of the html files the same way we do with the .cs files.  This way we can be sure to give credit to those who did the original coding along the way and we are complying with ethical development standards.  

@LifeGold If you can also take a picture of the slmapapi shown in your browser to show us if that is appearing in the browser that would be helpful if you can post it here as well.

Irishwolf Starfinder
Core Developer
Web and Network Design
Group Member
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
@LifeGold can you post a picture of the slmapapi.js in your browser so we can see what the map is showing?

Emperor Starfinder
CEO/ Founder
Core Developer
Web and Network Design
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by IrishwolfStarfinder** [comment]
@Lifegold Not a problem

@greythane Yes I agree licensing is something to be careful with.  The
line I was pointing at appears to be part of the copyright info shown at
the bottom of the page in the browser (usually shown in the footer
depending on the website design), however I could be incorrect in this
case.  I am aware of the discussion that is ongoing relating to the
licensing concerns our two projects.  A suggestion I would have would be
to put the licensing the same way we do with the .cs files at the top of
the html files as well while the licensing concerns are being worked out. 
This way we can be sure we are in compliance with proper ethical
development standards and are giving necessary and proper credit to all
developers who worked on the code prior to it being introduced into
Virtual Universe.

On a post note the slmapapi.js is in html/map

Irishwolf Starfinder
Core Developer
Web and Network Design
Group Member
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
It appears the licensing is still in tact.  The license at the top of the page, do not edit this.  That way we can be sure we aren't infringing on the licensing of previous developers

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by IrishwolfStarfinder** [comment]
I will go through each of the files to and be sure we have met the
licensing requirements before we roll it out into the main repository.

Irishwolf Starfinder
Core Developer
Website Design and Network Development
Work Group Member
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Good morning,

@greythane I checked the license for this proposal and it has not been altered. Line 748 that Irishwolf is referring to is the equivalent of line 727 in the original slmapapi.js which came from Aurora-Sim to WhiteCore-Sim which you edited from the Linden Labs copyright to WhiteCore's copyright.  it actually is a line displayed just below the world map in the browser.  It probably should display the name of the grid and not the name of the architecture.  i.e. {SystemName} instead as most grids will want that part of the copyright to show their grid name instead.  

As you know we will never allow credit to be removed for the developers before it came to Virtual Universe for any part of code.  This violates our team's Code of Ethical Development Standards and Code of Conduct..  

At any rate this is something to consider moving forward as we work through the licensing discussion our two projects is having. :)

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by IrishwolfStarfinder** [comment]
Good morning,

 @LifeGold the website is looking great thus far,  keep up the good work. 
I will start integrating it into the Virtual-Dev website so other Core
Developers of Virtual Universe and Greythane can have a look and make
recommendations for improvement.

 I just want to clarify something as it was brought to my attention.

 I am very well aware that Virtual Universe has code from WhiteCore-Sim in
its base and the fact that we do often merge in updates from
WhiteCore-Sim as deemed necessary by our core developers.  I do not hide
this fact from anyone I talk to about the Virtual Universe project nor do
I ever discourage proper credit being given where deserved and required. 
For anyone to assume that I am naive or just don't want people to know
that fact shows how incorrect their assumptions are.

 The reason I made the initial recommendations was because Virtual
Universe is its own project and not part of WhiteCore-Sim.  In fact it is
its own brand owned by the Second Galaxy Development Team.  It is also
very true as EmperorStarfinder has made very clear before that both
Virtual Universe is represented at the WhiteCore-Sim Development Team and
WhiteCore-Sim's team has a representative on our team to ensure the two
projects can communicate and work together on common goals both projects
share.

 The other fact people should know is when the Second Galaxy Development
Team was in the process of deciding what code should be part of the
Virtual Universe base code I was part of the group of 3 that did the
bench mark tests on Opensim, WhiteCore-Sim, and other architectures and
was pleased to recommend WhiteCore-Sim be used in the base code at the
Core Developer's meeting.

 So that being said, if in the future I say something that confuses you or
you do not understand, please ask before jumping to an assumption that
might be incorrect.  By asking I will be happy to clarify what I am
saying.

 @EmperorStarfinder Because LifeGold appears to be using Virtual Universe
at the base for his grid, and I think this is great to see, I recommend a
representative of his team be added as a collaborating partner in
accordance with Second Galaxy Development Team policy.

 Irishwolf Starfinder
 Core Developer
 Website and Network Development
 Work Group Member
 Grid Architecture Development Work Group
 Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Closing as this has been answered.
