### ISSUE TITLE
Scripting Problem

### ISSUE THREAD

**Issue by emperorstarfinder** [Virtual-Universe/Virtual-Universe#60]
### Notice

**If you are using WhiteCore-Sim please do not submit an issue report to Virtual Universe as we are unable to assist you.  Any issues reported to Virtual Universe which involve your use of WhiteCore-Sim will immediately be closed and you will be referred to WhiteCore-Sim.**

**In addition please do not submit issue reports regarding Virtual Universe to the WhiteCore-Sim issues tracker as they cannot help you and they will be immediately closed and you will be referred to Virtual Universe**

### Notice 2

**Effective August 1, 2016 - Any issues opened which do not have the provided questions answered will be closed immediately without further action.  The questions need to be answered to help provide us with as much information as possible to fix the bugs you find.  This has nothing to do with disliking reports or any individuals.  This has to do with getting to the root of the issues you report.  Thank you.**

### Issue Type

| Question      | Answer
| ------------- | ---------
| Bug?          | [yes|no]
| New feature?  | [yes|no]

### For Feature requests please answer the following

**Describe the feature you are requesting**:

**Has the feature been implemented by a similar project**:

**What other project similar to Virtual Universe has implemented the feature**:

**URL to where we can view the feature and or source code**:

### NOTE About Features

**The Second Galaxy Development Team will consider the features after we have seen enough interest by users of Virtual Universe.  The Feature must recieve at least five (5) core developers voting in favor of the feature for it to be included in a future release.**

### Steps to reproduce

    Hi all the next question. The problem with the moving objects on the servers of OpenSim and second life scripts work fine, but on WhiteCoreSim and the virtual Universe. See for yourself, and so many scripts are not working. And I tried many different, not exactly the same. https://www.youtube.com/watch?v=PaDaGo3gCQM&feature=youtu.be

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Server configuration

**Operating system**:

Ubuntu 14.04.4 LTS

**Web server:**

**Database:**

**Virtual Universe version:**
 
1.0.2

### Logs

Please make sure that Virtual Universe has made an log-file and include a link to it here

Note: This bug initially reported by LifeGold via WhiteCore-Sim: https://github.com/WhiteCoreSim/WhiteCore-Dev/issues/213

WhiteCore-Sim has placed this on hold in concurrance for the time being.  However LifeGold claims this issue exists in Virtual Universe as well.

**Comment by BritanyannStarfinder** [comment]
Morning,

I reviewed the issue indicated here in Issue #60 and the corresponding
issue reported at:
https://github.com/WhiteCoreSim/WhiteCore-Dev/issues/213

Additionally I have reviewed the video provided by LifeGold as part of my
review.

Findings:

It is a well known and established fact that Upstream Provider
WhiteCore-Sim uses the very old and well outdated DotNetEngine as its
scripting engine.  This is because when Aurora-Sim was created initially
DotNetEngine was the scripting engine used by Opensimulator. 
Opensimulator has sense upgraded their engine to their new XEngine which
while it to has problems is much more stable then DotNetEngine.  Virtual
Universe has inherited this from the Upstream provider unfortunately.

It is also well known that there are many problems with DotNetEngine
itself, which has never been something the Second Galaxy Development Team
has denied or rejected.

That being said, in reviewing the video from LifeGold and reviewing the
information @EmperorStarfinder has provided via our team's internal
tracker I am inclined to agree that initial review of the video itself
would appear to suggest an issue with the script itself and not the script
engine.  With that said there are some semantics going on with the
scripting engine itself that I really would not be surprised if they are
causing some issues as well.

However because the plan is to have the new scripting engine in place
prior to the release of Virtual Universe Version 1.0.3 RC1 I am inclined
to decline correcting this in DotNetEngine (if there is in fact a problem
with vehicle scripts) as the DotNetEngine will be removed as the scripting
engine upon successful replacement by the new engine.

You can watch developments of new features of Virtual Universe at:
https://github.com/Virtual-Universe/Virtual-Dev and even help test as well
which does help the team track down bugs.

Recommendation: Decline to fix in favor of new engine.


-- 
Britanyann Starfinder
Core Developer
Scripting Engine Developer
Work Group Member
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by BritanyannStarfinder** [comment]
Fix declined in favor of https://github.com/Virtual-Universe/Virtual-Dev/issues/8

**Comment by LifeGold** [comment]
And you are not going to go to XEngine or DotNetEngine will. And when will approximately release the virtual Universe version 1.0.3 and RC1?

**Comment by BritanyannStarfinder** [comment]
Hi LifeGold,

XEngine is the scripting engine used by Opensimulator.  We will be
replacing our current scripting engine with an upgraded state of the art
engine that will handle scripting more efficiently then it does currently.
 However it will not be a version of Opensimulator's XEngine.

I cannot say what the plans of the Upstream Provider is as far as their
scripting engine though I am told it is on their TODO list as well.

RC1 means Release Candidate 1.  This generally is released a few months
before the official release.  This is done to allow our larger user
community to kick the tires as it were and test the new version that we
are about to release.  This helps us find bugs and get them fixed faster
so our actual release will be much more stable.  The development and
release schedule for Virtual Universe Version 1.0.3 can be found in the
readme for the Virtual-Dev repository.

The Virtual-Dev repository is the development repository and is ahead of
the main Virtual-Universe repository.  If you are running a production
grade grid using Virtual Universe we strongly encourage you to use the
stable code in this repository here. This is because the development level
code may not always be stable.

-- 
Britanyann Starfinder
Core Developer
Scripting Engine Developer
Work Group Member
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
As I understand Korda released version 1.0.3 will need to install everything new since 1.0.2 it is not working, is there some patch or something like that for those who use version 1.0.2. Explain why this is, I have online about 1000+ people who are now playing on the server. I would not like after the release of 1.0.3 to demolish and put in a new one.

Translated with Google translator.

**Comment by BritanyannStarfinder** [comment]
Hi LifeGold,

Virtual Universe Stable Release is currently Virtual Universe 1.0.2.1. 
Virtual Universe Version 1.0.3 will not be out until next year per the
schedule on the Virtual-Dev repository.  When the time comes to upgrade
production grids to Virtual Universe Version 1.0.3 upgrading will not
affect the users on your grid.  We are unaware of problems with people
using Virtual Universe and upgrading the versions where it would affect
the users on their grid.  However when the time comes for upgrading grids
using Virtual Universe our development team members are always able to
assist as needed to get your grid upgraded and fully functional.

-- 
Britanyann Starfinder
Core Developer
Scripting Engine Developer
Work Group Member
Grid Architecture Development Work Group
Second Galaxy Development Team
